---
version: "3.5"

networks:
  aiassist:

services:
  # While the server is accessible, it is best to run the server
  # locally during development in order to get file watching and
  # auto reloading.
  server:
    build:
      context: ./server
      args:
        GIT_REVISION: "${commit}"
    ports:
      - "8003:8080"
    environment:
      OPENAI_KEY: "${openai_key}"
      WHISPER_TRANSCRIBE_ENDPOINT: http://whisper:8080/asr
      REDIS_URL: redis://redis:6379
    networks:
      - aiassist

  whisper:
    restart: always
    build:
      context: ./whisper-asr-webservice
      args:
        ASR_MODEL: tiny
    ports:
      - "9000:8080"
    networks:
      - aiassist
    entrypoint:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8080",
        "--workers",
        "1",
        "--timeout",
        "0",
        "app.webservice:app",
        "-k",
        "uvicorn.workers.UvicornWorker",
      ]

  redis:
    image: "redis:7-alpine"
    restart: always
    networks:
      - aiassist
    ports:
      - 6379:6379
