---
version: "3.5"

networks:
  aiassist:

services:
  whisper:
    restart: always
    build:
      context: ./whisper-asr-webservice
      args:
        ASR_MODEL: tiny
    ports:
      - "9000:8080"
    networks:
      - aiassist
    entrypoint:
      [
        "gunicorn",
        "--bind",
        "0.0.0.0:8080",
        "--workers",
        "1",
        "--timeout",
        "0",
        "app.webservice:app",
        "-k",
        "uvicorn.workers.UvicornWorker",
      ]

  redis:
    image: "redis:7-alpine"
    restart: always
    networks:
      - aiassist
    ports:
      - 6379:6379
