//
// ArgumentTypeOneOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ArgumentTypeOneOf1: String, Codable, CaseIterable {
    case number = "number"
}
