//
// ArgumentTypeOneOf2.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ArgumentTypeOneOf2: String, Codable, CaseIterable {
    case boolean = "boolean"
}
