//
// ArgumentType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ArgumentType: Codable, JSONEncodable, Hashable {
    case typeArgumentTypeOneOf(ArgumentTypeOneOf)
    case typeArgumentTypeOneOf1(ArgumentTypeOneOf1)
    case typeArgumentTypeOneOf2(ArgumentTypeOneOf2)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeArgumentTypeOneOf(let value):
            try container.encode(value)
        case .typeArgumentTypeOneOf1(let value):
            try container.encode(value)
        case .typeArgumentTypeOneOf2(let value):
            try container.encode(value)
        }
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let value = try? container.decode(ArgumentTypeOneOf.self) {
            self = .typeArgumentTypeOneOf(value)
        } else if let value = try? container.decode(ArgumentTypeOneOf1.self) {
            self = .typeArgumentTypeOneOf1(value)
        } else if let value = try? container.decode(ArgumentTypeOneOf2.self) {
            self = .typeArgumentTypeOneOf2(value)
        } else {
            throw DecodingError.typeMismatch(Self.Type.self, .init(codingPath: decoder.codingPath, debugDescription: "Unable to decode instance of ArgumentType"))
        }
    }
}

