//
// ArgumentTypeOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ArgumentTypeOneOf: String, Codable, CaseIterable {
    case string = "string"
}
