//
// ArgumentParserOneOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ArgumentParserOneOf: String, Codable, CaseIterable {
    case naturallanguagedatetime = "naturalLanguageDateTime"
}
