//
// FunctionDefinition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FunctionDefinition: Codable, JSONEncodable, Hashable {

    public var description: String
    public var args: [AnyCodable]
    public var triggerTokens: [String]?

    public init(description: String, args: [AnyCodable], triggerTokens: [String]? = nil) {
        self.description = description
        self.args = args
        self.triggerTokens = triggerTokens
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case args
        case triggerTokens
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(description, forKey: .description)
        try container.encode(args, forKey: .args)
        try container.encodeIfPresent(triggerTokens, forKey: .triggerTokens)
    }
}

