//
// FunctionDefinitionAllOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FunctionDefinitionAllOf: Codable, JSONEncodable, Hashable {

    public var description: String
    public var args: [AnyCodable]

    public init(description: String, args: [AnyCodable]) {
        self.description = description
        self.args = args
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case description
        case args
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(description, forKey: .description)
        try container.encode(args, forKey: .args)
    }
}

