//
// ModelsAssist000Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsAssist000Output: Codable, JSONEncodable, Hashable {

    public enum Model: String, Codable, CaseIterable {
        case assist000 = "assist-000"
    }
    public var model: Model
    public var request: String
    public var functionCalls: [AnyOfobjectobjectAnyTypeobject]
    public var missingRequestContext: ModelsAssist000OutputAnyOf1MissingRequestContext

    public init(model: Model, request: String, functionCalls: [AnyOfobjectobjectAnyTypeobject], missingRequestContext: ModelsAssist000OutputAnyOf1MissingRequestContext) {
        self.model = model
        self.request = request
        self.functionCalls = functionCalls
        self.missingRequestContext = missingRequestContext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case model
        case request
        case functionCalls
        case missingRequestContext
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(model, forKey: .model)
        try container.encode(request, forKey: .request)
        try container.encode(functionCalls, forKey: .functionCalls)
        try container.encode(missingRequestContext, forKey: .missingRequestContext)
    }
}

