//
// ModelsCode000Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsCode000Output: Codable, JSONEncodable, Hashable {

    public enum Model: String, Codable, CaseIterable {
        case code000 = "code-000"
    }
    public var model: Model
    public var targetLanguage: String
    public var request: String
    public var result: String

    public init(model: Model, targetLanguage: String, request: String, result: String) {
        self.model = model
        self.targetLanguage = targetLanguage
        self.request = request
        self.result = result
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case model
        case targetLanguage
        case request
        case result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(model, forKey: .model)
        try container.encode(targetLanguage, forKey: .targetLanguage)
        try container.encode(request, forKey: .request)
        try container.encode(result, forKey: .result)
    }
}

