//
// ModelsAssist000OutputAnyOf1MissingRequestContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsAssist000OutputAnyOf1MissingRequestContext: Codable, JSONEncodable, Hashable {

    public enum Text: String, Codable, CaseIterable {
        case string = "string"
    }
    public enum Language: String, Codable, CaseIterable {
        case string = "string"
    }
    public var text: Text?
    public var language: Language?

    public init(text: Text? = nil, language: Language? = nil) {
        self.text = text
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(language, forKey: .language)
    }
}

