//
// ModelsTranslate000Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsTranslate000Input: Codable, JSONEncodable, Hashable {

    public var targetLanguage: String
    public var request: String

    public init(targetLanguage: String, request: String) {
        self.targetLanguage = targetLanguage
        self.request = request
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case targetLanguage
        case request
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(targetLanguage, forKey: .targetLanguage)
        try container.encode(request, forKey: .request)
    }
}

