//
// ModelsAssist000Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsAssist000Input: Codable, JSONEncodable, Hashable {

    public var requestContext: AnyCodable
    public var request: String

    public init(requestContext: AnyCodable, request: String) {
        self.requestContext = requestContext
        self.request = request
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestContext
        case request
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestContext, forKey: .requestContext)
        try container.encode(request, forKey: .request)
    }
}

