//
// ModelsWhisper000Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsWhisper000Output: Codable, JSONEncodable, Hashable {

    public enum Model: String, Codable, CaseIterable {
        case whisper000 = "whisper-000"
    }
    public var model: Model
    public var transcribed: String

    public init(model: Model, transcribed: String) {
        self.model = model
        self.transcribed = transcribed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case model
        case transcribed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(model, forKey: .model)
        try container.encode(transcribed, forKey: .transcribed)
    }
}

