//
// ModelsPassthroughOpenai000Input.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsPassthroughOpenai000Input: Codable, JSONEncodable, Hashable {

    public var openAiModel: String
    public var request: String

    public init(openAiModel: String, request: String) {
        self.openAiModel = openAiModel
        self.request = request
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case openAiModel
        case request
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(openAiModel, forKey: .openAiModel)
        try container.encode(request, forKey: .request)
    }
}

