//
// ModelsAssist000InputAnyOfRequestContext.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsAssist000InputAnyOfRequestContext: Codable, JSONEncodable, Hashable {

    public var text: String?
    public var language: String?

    public init(text: String? = nil, language: String? = nil) {
        self.text = text
        self.language = language
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case language
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(language, forKey: .language)
    }
}

