//
// ModelsAssist000OutputAnyOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsAssist000OutputAnyOf1: Codable, JSONEncodable, Hashable {

    public var missingRequestContext: ModelsAssist000OutputAnyOf1MissingRequestContext

    public init(missingRequestContext: ModelsAssist000OutputAnyOf1MissingRequestContext) {
        self.missingRequestContext = missingRequestContext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case missingRequestContext
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(missingRequestContext, forKey: .missingRequestContext)
    }
}

