//
// ModelsAssist000InputAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsAssist000InputAnyOf: Codable, JSONEncodable, Hashable {

    public var requestContext: ModelsAssist000InputAnyOfRequestContext

    public init(requestContext: ModelsAssist000InputAnyOfRequestContext) {
        self.requestContext = requestContext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case requestContext
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(requestContext, forKey: .requestContext)
    }
}

