//
// ModelsPassthroughOpenai000Output.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModelsPassthroughOpenai000Output: Codable, JSONEncodable, Hashable {

    public enum Model: String, Codable, CaseIterable {
        case passthroughOpenai000 = "passthrough-openai-000"
    }
    public var model: Model
    public var openAiModel: String
    public var request: String
    public var result: String

    public init(model: Model, openAiModel: String, request: String, result: String) {
        self.model = model
        self.openAiModel = openAiModel
        self.request = request
        self.result = result
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case model
        case openAiModel
        case request
        case result
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(model, forKey: .model)
        try container.encode(openAiModel, forKey: .openAiModel)
        try container.encode(request, forKey: .request)
        try container.encode(result, forKey: .result)
    }
}

