//
// PostSessionsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostSessionsRequest: Codable, JSONEncodable, Hashable {

    public var modelConfigurations: [PostSessionsRequestAllOfModelConfigurationsInner]
    public var configuration: SessionConfiguration?

    public init(modelConfigurations: [PostSessionsRequestAllOfModelConfigurationsInner], configuration: SessionConfiguration? = nil) {
        self.modelConfigurations = modelConfigurations
        self.configuration = configuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case modelConfigurations
        case configuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(modelConfigurations, forKey: .modelConfigurations)
        try container.encodeIfPresent(configuration, forKey: .configuration)
    }
}

