//
// PostSessionsRequestAllOfModelConfigurationsInnerAnyOf.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostSessionsRequestAllOfModelConfigurationsInnerAnyOf: Codable, JSONEncodable, Hashable {

    public enum Model: String, Codable, CaseIterable {
        case noop = "noop"
    }
    public var model: Model

    public init(model: Model) {
        self.model = model
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case model
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(model, forKey: .model)
    }
}

