//
// PostSessionsRequestAllOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostSessionsRequestAllOf1: Codable, JSONEncodable, Hashable {

    public var configuration: SessionConfiguration?

    public init(configuration: SessionConfiguration? = nil) {
        self.configuration = configuration
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case configuration
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(configuration, forKey: .configuration)
    }
}

