//
// PostSessions200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PostSessions200Response: Codable, JSONEncodable, Hashable {

    public var session: Session
    public var builtinFunctions: [String: FunctionDefinition]

    public init(session: Session, builtinFunctions: [String: FunctionDefinition]) {
        self.session = session
        self.builtinFunctions = builtinFunctions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case session
        case builtinFunctions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(session, forKey: .session)
        try container.encode(builtinFunctions, forKey: .builtinFunctions)
    }
}

