//
// SessionAllOf1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionAllOf1: Codable, JSONEncodable, Hashable {

    public var outputAwaitingContext: AnyOfmodelsAssist000OutputobjectmodelsTranslate000OutputmodelsCode000OutputmodelsWhisper000OutputmodelsPassthroughOpenai000Output?

    public init(outputAwaitingContext: AnyOfmodelsAssist000OutputobjectmodelsTranslate000OutputmodelsCode000OutputmodelsWhisper000OutputmodelsPassthroughOpenai000Output? = nil) {
        self.outputAwaitingContext = outputAwaitingContext
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outputAwaitingContext
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(outputAwaitingContext, forKey: .outputAwaitingContext)
    }
}

