//
// SessionConfiguration.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SessionConfiguration: Codable, JSONEncodable, Hashable {

    public var locale: String
    public var maxResponseTokens: Double
    public var bestOf: Double
    public var disabledBuiltinFunctions: [SessionConfigurationDisabledBuiltinFunctionsInner]

    public init(locale: String, maxResponseTokens: Double, bestOf: Double, disabledBuiltinFunctions: [SessionConfigurationDisabledBuiltinFunctionsInner]) {
        self.locale = locale
        self.maxResponseTokens = maxResponseTokens
        self.bestOf = bestOf
        self.disabledBuiltinFunctions = disabledBuiltinFunctions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locale
        case maxResponseTokens
        case bestOf
        case disabledBuiltinFunctions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locale, forKey: .locale)
        try container.encode(maxResponseTokens, forKey: .maxResponseTokens)
        try container.encode(bestOf, forKey: .bestOf)
        try container.encode(disabledBuiltinFunctions, forKey: .disabledBuiltinFunctions)
    }
}

