//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ArgumentParser: String, Codable, Equatable, CaseIterable {
    case naturalLanguageDateTime = "naturalLanguageDateTime"
}
