//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AssistResultNeedsRequestContext: APIModel {

    public enum `Type`: String, Codable, Equatable, CaseIterable {
        case needsRequestContext = "needs_request_context"
    }

    public var type: `Type`

    public var missingRequestContext: RequestContextRequirement

    public init(type: `Type`, missingRequestContext: RequestContextRequirement) {
        self.type = type
        self.missingRequestContext = missingRequestContext
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        type = try container.decode("type")
        missingRequestContext = try container.decode("missingRequestContext")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(type, forKey: "type")
        try container.encode(missingRequestContext, forKey: "missingRequestContext")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AssistResultNeedsRequestContext else { return false }
      guard self.type == object.type else { return false }
      guard self.missingRequestContext == object.missingRequestContext else { return false }
      return true
    }

    public static func == (lhs: AssistResultNeedsRequestContext, rhs: AssistResultNeedsRequestContext) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
