//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AssistResultOK: APIModel {

    public enum `Type`: String, Codable, Equatable, CaseIterable {
        case ok = "ok"
    }

    public var type: `Type`

    public var commands: [Command]

    public init(type: `Type`, commands: [Command]) {
        self.type = type
        self.commands = commands
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        type = try container.decode("type")
        commands = try container.decodeArray("commands")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(type, forKey: "type")
        try container.encode(commands, forKey: "commands")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AssistResultOK else { return false }
      guard self.type == object.type else { return false }
      guard self.commands == object.commands else { return false }
      return true
    }

    public static func == (lhs: AssistResultOK, rhs: AssistResultOK) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
