//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class BooleanValueRequirement: APIModel {

    public enum `Type`: String, Codable, Equatable, CaseIterable {
        case boolean = "boolean"
    }

    public var type: `Type`

    public init(type: `Type`) {
        self.type = type
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        type = try container.decode("type")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(type, forKey: "type")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? BooleanValueRequirement else { return false }
      guard self.type == object.type else { return false }
      return true
    }

    public static func == (lhs: BooleanValueRequirement, rhs: BooleanValueRequirement) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
