//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class CommandExecuted: APIModel {

    public enum `Type`: String, Codable, Equatable, CaseIterable {
        case executed = "executed"
    }

    public var id: String

    public var type: `Type`

    public var name: String

    public var args: [Value]

    public var returnValue: Value

    public init(id: String, type: `Type`, name: String, args: [Value], returnValue: Value) {
        self.id = id
        self.type = type
        self.name = name
        self.args = args
        self.returnValue = returnValue
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        id = try container.decode("id")
        type = try container.decode("type")
        name = try container.decode("name")
        args = try container.decodeArray("args")
        returnValue = try container.decode("returnValue")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(id, forKey: "id")
        try container.encode(type, forKey: "type")
        try container.encode(name, forKey: "name")
        try container.encode(args, forKey: "args")
        try container.encode(returnValue, forKey: "returnValue")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? CommandExecuted else { return false }
      guard self.id == object.id else { return false }
      guard self.type == object.type else { return false }
      guard self.name == object.name else { return false }
      guard self.args == object.args else { return false }
      guard self.returnValue == object.returnValue else { return false }
      return true
    }

    public static func == (lhs: CommandExecuted, rhs: CommandExecuted) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
