//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ImplementationUnnecessaryBuiltinCommand: String, Codable, Equatable, CaseIterable {
    case math = "math"
    case time = "time"
    case translate = "translate"
    case generateCode = "generateCode"
    case editProse = "editProse"
    case editCode = "editCode"
}
