//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum KnownBuiltinCommand: String, Codable, Equatable, CaseIterable {
    case display = "display"
    case write = "write"
    case answer = "answer"
    case math = "math"
    case time = "time"
    case editProse = "editProse"
    case editCode = "editCode"
    case generateCode = "generateCode"
    case translate = "translate"
    case fail = "fail"
}
