//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ModelsCode000Input: APIModel {

    public var programmingLanguage: String

    public var request: String

    public init(programmingLanguage: String, request: String) {
        self.programmingLanguage = programmingLanguage
        self.request = request
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        programmingLanguage = try container.decode("programmingLanguage")
        request = try container.decode("request")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(programmingLanguage, forKey: "programmingLanguage")
        try container.encode(request, forKey: "request")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ModelsCode000Input else { return false }
      guard self.programmingLanguage == object.programmingLanguage else { return false }
      guard self.request == object.request else { return false }
      return true
    }

    public static func == (lhs: ModelsCode000Input, rhs: ModelsCode000Input) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
