//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ModelsAssist002Configuration: APIModel {

    public enum Model: String, Codable, Equatable, CaseIterable {
        case assist002 = "assist-002"
    }

    public enum OpenaiModel: String, Codable, Equatable, CaseIterable {
        case gpt4 = "gpt-4"
        case gpt35Turbo = "gpt-3.5-turbo"
    }

    public var model: Model

    public var commands: [String: CommandDefinition]

    public var openaiModel: OpenaiModel?

    public init(model: Model, commands: [String: CommandDefinition], openaiModel: OpenaiModel? = nil) {
        self.model = model
        self.commands = commands
        self.openaiModel = openaiModel
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        model = try container.decode("model")
        commands = try container.decode("commands")
        openaiModel = try container.decodeIfPresent("openaiModel")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(model, forKey: "model")
        try container.encode(commands, forKey: "commands")
        try container.encodeIfPresent(openaiModel, forKey: "openaiModel")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ModelsAssist002Configuration else { return false }
      guard self.model == object.model else { return false }
      guard self.commands == object.commands else { return false }
      guard self.openaiModel == object.openaiModel else { return false }
      return true
    }

    public static func == (lhs: ModelsAssist002Configuration, rhs: ModelsAssist002Configuration) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
