//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ResultFinished: APIModel {

    public enum `Type`: String, Codable, Equatable, CaseIterable {
        case finished = "finished"
    }

    public var type: `Type`

    public var results: [Value]

    public init(type: `Type`, results: [Value]) {
        self.type = type
        self.results = results
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        type = try container.decode("type")
        results = try container.decodeArray("results")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(type, forKey: "type")
        try container.encode(results, forKey: "results")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ResultFinished else { return false }
      guard self.type == object.type else { return false }
      guard self.results == object.results else { return false }
      return true
    }

    public static func == (lhs: ResultFinished, rhs: ResultFinished) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
