//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ResultPendingCommands: APIModel {

    public enum `Type`: String, Codable, Equatable, CaseIterable {
        case pendingCommands = "pending_commands"
    }

    public var type: `Type`

    public var pendingCommands: [Command]

    public var resolvedCommands: [CommandExecuted]

    public init(type: `Type`, pendingCommands: [Command], resolvedCommands: [CommandExecuted]) {
        self.type = type
        self.pendingCommands = pendingCommands
        self.resolvedCommands = resolvedCommands
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        type = try container.decode("type")
        pendingCommands = try container.decodeArray("pendingCommands")
        resolvedCommands = try container.decodeArray("resolvedCommands")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(type, forKey: "type")
        try container.encode(pendingCommands, forKey: "pendingCommands")
        try container.encode(resolvedCommands, forKey: "resolvedCommands")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ResultPendingCommands else { return false }
      guard self.type == object.type else { return false }
      guard self.pendingCommands == object.pendingCommands else { return false }
      guard self.resolvedCommands == object.resolvedCommands else { return false }
      return true
    }

    public static func == (lhs: ResultPendingCommands, rhs: ResultPendingCommands) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
