//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class StringValueRequirement: APIModel {

    public enum `Type`: String, Codable, Equatable, CaseIterable {
        case string = "string"
    }

    public var type: `Type`

    public var description: String

    public init(type: `Type`, description: String) {
        self.type = type
        self.description = description
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        type = try container.decode("type")
        description = try container.decode("description")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(type, forKey: "type")
        try container.encode(description, forKey: "description")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? StringValueRequirement else { return false }
      guard self.type == object.type else { return false }
      guard self.description == object.description else { return false }
      return true
    }

    public static func == (lhs: StringValueRequirement, rhs: StringValueRequirement) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
