//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ValueType: String, Codable, Equatable, CaseIterable {
    case string = "string"
    case number = "number"
    case boolean = "boolean"
}
