// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/api/session/_middleware.ts";
import * as $1 from "./routes/api/session/requests.ts";
import * as $2 from "./routes/api/session/transcriptions.ts";
import * as $3 from "./routes/api/sessions.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/AudioPrompt.tsx";
import * as $$1 from "./islands/TextPrompt.tsx";

const manifest = {
  routes: {
    "./routes/api/session/_middleware.ts": $0,
    "./routes/api/session/requests.ts": $1,
    "./routes/api/session/transcriptions.ts": $2,
    "./routes/api/sessions.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/AudioPrompt.tsx": $$0,
    "./islands/TextPrompt.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
