//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ErrorType: APIModel {

    public var error: String

    public init(error: String) {
        self.error = error
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        error = try container.decode("error")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(error, forKey: "error")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ErrorType else { return false }
      guard self.error == object.error else { return false }
      return true
    }

    public static func == (lhs: ErrorType, rhs: ErrorType) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
