//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ModelsNoopInput: APIModel {

    public enum Request: String, Codable, Equatable, CaseIterable {
        case noop = "noop"
    }

    public var request: Request

    public init(request: Request) {
        self.request = request
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        request = try container.decode("request")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(request, forKey: "request")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ModelsNoopInput else { return false }
      guard self.request == object.request else { return false }
      return true
    }

    public static func == (lhs: ModelsNoopInput, rhs: ModelsNoopInput) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
