//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ModelsTranslate000Input: APIModel {

    public var targetLanguage: String

    public var request: String

    public init(targetLanguage: String, request: String) {
        self.targetLanguage = targetLanguage
        self.request = request
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        targetLanguage = try container.decode("targetLanguage")
        request = try container.decode("request")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(targetLanguage, forKey: "targetLanguage")
        try container.encode(request, forKey: "request")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ModelsTranslate000Input else { return false }
      guard self.targetLanguage == object.targetLanguage else { return false }
      guard self.request == object.request else { return false }
      return true
    }

    public static func == (lhs: ModelsTranslate000Input, rhs: ModelsTranslate000Input) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
