//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ModelsPassthroughOpenai000Configuration: APIModel {

    public enum Model: String, Codable, Equatable, CaseIterable {
        case passthroughOpenai000 = "passthrough-openai-000"
    }

    public var model: Model

    public init(model: Model) {
        self.model = model
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        model = try container.decode("model")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(model, forKey: "model")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ModelsPassthroughOpenai000Configuration else { return false }
      guard self.model == object.model else { return false }
      return true
    }

    public static func == (lhs: ModelsPassthroughOpenai000Configuration, rhs: ModelsPassthroughOpenai000Configuration) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
