//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ModelsNoopOutput: APIModel {

    public enum Model: String, Codable, Equatable, CaseIterable {
        case noop = "noop"
    }

    public enum Result: String, Codable, Equatable, CaseIterable {
        case noop = "noop"
    }

    public var model: Model

    public var result: Result

    public init(model: Model, result: Result) {
        self.model = model
        self.result = result
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        model = try container.decode("model")
        result = try container.decode("result")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(model, forKey: "model")
        try container.encode(result, forKey: "result")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ModelsNoopOutput else { return false }
      guard self.model == object.model else { return false }
      guard self.result == object.result else { return false }
      return true
    }

    public static func == (lhs: ModelsNoopOutput, rhs: ModelsNoopOutput) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
