//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ModelsPassthroughOpenai000Input: APIModel {

    public var openAiModel: String

    public var request: String

    public init(openAiModel: String, request: String) {
        self.openAiModel = openAiModel
        self.request = request
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        openAiModel = try container.decode("openAiModel")
        request = try container.decode("request")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(openAiModel, forKey: "openAiModel")
        try container.encode(request, forKey: "request")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ModelsPassthroughOpenai000Input else { return false }
      guard self.openAiModel == object.openAiModel else { return false }
      guard self.request == object.request else { return false }
      return true
    }

    public static func == (lhs: ModelsPassthroughOpenai000Input, rhs: ModelsPassthroughOpenai000Input) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
